on:
  push:
    - workflows: [build-package-workflow, docker-workflow]
      filter:
        branches: ["main"]
  pull_request:
    - workflows: build-package-workflow
      filter:
        source_branches: ["**", "!test**"]
        target_branches: "main"

workflows:
  build-package-workflow:
    tasks:
      - build-package-task
  docker-workflow:
    tasks:
      - build-push-image-task

tasks:
  - name: build-package-task
    cubes:
      - name: setup-jdk
        script:
          - sudo apt install openjdk-17-jdk -y
      - name: test
        script:
          - ./gradlew check
      - name: package
        script:
          - ./gradlew build
        artifacts:
          paths:
            - build/libs/memes-tv-0.0.1-SNAPSHOT.jar
  - name: build-push-image-task
    cubes:
      - name: setup-jdk
        script:
          - sudo apt install openjdk-17-jdk -y
      - name: build
        script:
          - ./gradlew build
      - name: docker-login
        env:
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        script:
          - echo $DOCKER_PASSWORD | docker login --username oauth --password-stdin cr.yandex
      - name: build-image
        script:
          - ./gradlew bootBuildImage
          - docker tag docker.io/library/memes-tv:0.0.1-SNAPSHOT cr.yandex/crph26nr2d2ds65t2m7b/memes-tv:0.0.1-SNAPSHOT
      - name: push-image
          - docker push cr.yandex/crph26nr2d2ds65t2m7b/memes-tv:0.0.1-SNAPSHOT
