on:
  push:
    - workflows: [build-package-workflow]
      filter:
        branches: ["main"]

workflows:
  build-package-workflow:
    tasks:
      - build-package-task

tasks:
  - name: build-package-task
    cubes:
      - name: yc-login
        env:
          #YC_TOKEN: ${{ secrets.YC_TOKEN }}
          YC_CLOUD_ID: b1g57p6cf47buiqb13l9
          YC_FOLDER_ID: b1g69j298i7l91gblj93
        script:
          #- yc config set token $YC_TOKEN
          - curl -sSL https://storage.yandexcloud.net/yandexcloud-yc/install.sh | bash
          - exec -l $SHELL
          - yc config set cloud-id $YC_CLOUD_ID
          - yc config set folder-id $YC_FOLDER_ID
          - yc container registry configure-docker
      - name: setup-jdk
        script:
          - sudo apt install openjdk-17-jdk -y
      - name: test
        script:
          - ./gradlew check
      - name: package
        script:
          - ./gradlew assemble
        artifacts:
          paths:
            - build/libs/memes-tv-0.0.1-SNAPSHOT.jar
      - name: build-image
        script:
          - ./gradlew bootBuildImage
          - docker tag docker.io/library/memes-tv:0.0.1-SNAPSHOT cr.yandex/crph26nr2d2ds65t2m7b/memes-tv:0.0.1-SNAPSHOT
      - name: push-image
        script:
          - docker push cr.yandex/crph26nr2d2ds65t2m7b/memes-tv:0.0.1-SNAPSHOT
